export * from './RouteSetting';
export * from './product/productDetail.route';
export * from './magazine/magazine.route';
export * from './notification/notification.route';
export * from './auth/auth';
export * from './store/store.update.route';
export * from './comment/comment.list.route';
export * from './order/order.route';
export * from './profile/profile.route';