export * from './auth/authAPI';
export * from './store/storeAPI';
export * from './pick/pickAPI';
export * from './notification/commonAPI';
export * from './product/product.api';
export * from './store/store.api';
export * from './user/user.api';
export * from './recipient/recipient.api';
export * from './user/user.pick.api';
export * from './user/user.favorite.api';
export * from './home/home.api';
export * as AuthAPI from './auth/auth.api';
export * from './feedbacks/feedback.api';
export * from './onboarding/styles.api';
export * from './magazine/magazine.api';
export * from './checkout/voucher.api';
export * from './order/order.api';
